name: Build

on:
  push:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  dists-and-docs:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U -r requirements.txt

      - name: Build distributions
        run: |
          python ./setup.py sdist bdist_wheel

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: distributions
      #     path: dist/*

      - name: Install package
        run: |
          pip install -e .[docs,speed,voice]

      - name: Build docs
        shell: bash
        run: |
          cd docs
          sphinx-build -b html -D language=en -j auto -a -n -T -W --keep-going . _build/html
        env:
          DOCS_LANGUAGE: en

      # - name: Upload docs
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: docs-en
      #     path: docs/_build/html/*
