name: build

on:
  push:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  dists-and-docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.x' ]

    name: dists & docs ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade build

      - name: Build distributions
        run: |
          python -m build

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: distributions
      #     path: dist/*

      - name: Install package
        run: |
          pip install -e .[docs,speed,voice]

      - name: Build docs
        shell: bash
        run: |
          cd docs

          EXIT_STATUS=0
          # Build English docs
          sphinx-build -b html -D language=en -a -n -T -W --keep-going . _build_en || EXIT_STATUS=$?
          # Build Japanese docs
          sphinx-build -b html -D language=ja -a -n -T -W --keep-going . _build_ja || EXIT_STATUS=$?

          exit ${EXIT_STATUS}

      # - name: Upload EN docs
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: docs-en
      #     path: docs/_build_en/*

      # - name: Upload JA docs
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: docs-ja
      #     path: docs/_build_ja/*
