
name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit -r . || true
      - run: black --check . || true
      - run: codespell --ignore-words-list="nd" --quiet-level=2 || true  #  --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: isort --profile black . || true
      - run: mypy . || true
      - run: pip install -r requirements.txt
      - run: pytest . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
